name: Client Onboarding Form
description: Official onboarding submission
title: "[Onboarding]: "
labels: ["onboarding"]

body:
  - type: input
    id: full_name
    attributes:
      label: Client Full Name
      placeholder: Enter full legal name
    validations:
      required: true

  - type: input
    id: email
    attributes:
      label: Client Email Address
      placeholder: example@email.com
    validations:
      required: true

  - type: dropdown
    id: service
    attributes:
      label: Service Requested
      options:
        - Consultation
        - Application Support
        - Documentation Review
        - Other
    validations:
      required: true

  - type: input
    id: date
    attributes:
      label: Date of Submission
      placeholder: YYYY-MM-DD
    validations:
      required: true

  - type: checkboxes
    id: declaration
    attributes:
      label: Declaration
      options:
        - label: I confirm the information provided is accurate.
          required: true
